### ISSUE TITLE
one problem "failed to start java"

### ISSUE THREAD

**Issue by yuxw75** [fredlund/JavaErlang#10]
*** Warning: failed trying to connect to Java node 'javaNode_298@127.0.0.1'
'javaNode_298@127.0.0.1': failed to connect at try 2 with reason timeout
*** Error: void: failed to start Java

**Comment by yuxw75** [comment]
because of cookie  not the erlang default,if I set cookie not default,then can't connect to java node

**Comment by fredlund** [comment]
There is now an option setcookie for start_node to be able to set the cookie for a java node.
Example: java:start_node([{setcookie,"ABC"}]).

Thanks for the problem report.
