### ISSUE TITLE
EQC not present

### ISSUE THREAD

**Issue by skvamme** [fredlund/JavaErlang#17]
Hi,
Thank you for JavaErlang. Had some problem with tests:

./rebar3 eunit -v gives the following error

_build/test/lib/java_erlang/test/qc/hashset_test.erl:39: can't find include lib "eqc/include/eqc.hrl"

basho had a similar problem
https://github.com/basho/riak_kv/pull/787

**Comment by fredlund** [comment]
Hello,

you are right, this is a problem and the solution should be similar to the basho one. I am away over the weekend without good internet access but will look into this as soon as possible. Thanks for the report!

**Comment by fredlund** [comment]
I decided to move the quickcheck tests from the test directory to a top level qc directory instead. This should make rebar3 eunit work, and matches what the quickcheck rebar3 plugin expects too (but not tested :-)
