### ISSUE TITLE
rebar3 compile error

### ISSUE THREAD

**Issue by yuxw75** [fredlund/JavaErlang#8]
rebar3 compile
===> Verifying dependencies...
===> Compiling java_erlang
javac -g -deprecation -Werror -sourcepath ./java_src -classpath ./priv/javassist.jar: =ERROR REPORT==== 8-Sep-2015::12:25:38 === Error in process <0.2.0> with exit value: {badarg,[{io,format,[<0.24.0>,"~s",[{error,bad_name}]],[]},          {erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,669}]},          {init,start_it,1,[]},          {init,start_em,1,[]}]}/OtpErlang.jar -d ./java_src ./java_src/javaErlang/JavaObjectEntry.java ./java_src/javaErlang/ProxyInstanceFactory.java ./java_src/javaErlang/OtpStatusHandler.java ./java_src/javaErlang/ProxyFactoryClass.java ./java_src/javaErlang/ErlangObjectKey.java ./java_src/javaErlang/Tags.java ./java_src/javaErlang/ThreadMsgHandler.java ./java_src/javaErlang/IntKey.java ./java_src/javaErlang/RefEqualsObject.java ./java_src/javaErlang/JavaObjectKey.java ./java_src/javaErlang/JavaErlang.java ./java_src/javaErlang/testing/Test2.java ./java_src/javaErlang/testing/Test.java ./java_src/javaErlang/ProxyHandler.java ./java_src/javaErlang/ErlangObjectRef.java
/bin/sh: 1: cannot open 0.2.0: No such file
make: *** [priv/JavaErlang.jar] Error 2
===> Hook for compile failed!

**Comment by yuxw75** [comment]
The reason is that I don't install jinterface when installing erlang because of lacking jdk.

**Comment by yuxw75** [comment]
why memory seizure is more and more,i have choose the gc option.

**Comment by fredlund** [comment]
Thanks for the information. Maybe we should try to give a better error message if jinterface is missing. Please also let me know how well the gc option works, it hasn't been used so much as far as I know.

**Comment by yuxw75** [comment]
gc options worked well. there's another problem. that is,afterI terminate java node,there's still java process running in linux system. such as:
ubuntu@VM-66-105-ubuntu:/data/release/mytest$ ps -xf | grep java
 9782 pts/0    S+     0:00      \_ grep --color=auto java
 2134 ?        Ssl    5:31 /usr/bin/java -cp ./miui_sb7.jar:/usr/local/lib/erlan                                                      g/lib/jinterface-1.6/priv/OtpErlang.jar:/usr/local/lib/erlang/lib/java_erlang-1.                                                      3.1/priv/JavaErlang.jar:/usr/local/lib/erlang/lib/java_erlang-1.3.1/priv/javassi                                                      st.jar javaErlang.JavaErlang javaNode_199@203.195.161.84
 2120 ?        Ssl    5:32 /usr/bin/java -cp ./miui_sb7.jar:/usr/local/lib/erlan                                                      g/lib/jinterface-1.6/priv/OtpErlang.jar:/usr/local/lib/erlang/lib/java_erlang-1.                                                      3.1/priv/JavaErlang.jar:/usr/local/lib/erlang/lib/java_erlang-1.3.1/priv/javassi                                                      st.jar javaErlang.JavaErlang javaNode_100@203.195.161.84
 1849 ?        Ssl    5:31 /usr/bin/java -cp ./miui_sb7.jar:/usr/local/lib/erlan                                                      g/lib/jinterface-1.6/priv/OtpErlang.jar:/usr/local/lib/erlang/lib/java_erlang-1.                                                      3.1/priv/JavaErlang.jar:/usr/local/lib/erlang/lib/java_erlang-1.3.1/priv/javassi                                                      st.jar javaErlang.JavaErlang javaNode_100@203.195.161.84
 8481 ?        Ssl    3:23              \_ /usr/bin/java -cp ./miui_sb7.jar:/usr                                                      /local/lib/erlang/lib/jinterface-1.6/priv/OtpErlang.jar:/usr/local/lib/erlang/li                                                      b/java_erlang-1.3.1/priv/JavaErlang.jar:/usr/local/lib/erlang/lib/java_erlang-1.                                                      3.1/priv/javassist.jar javaErlang.JavaErlang javaNode_103@203.195.161.84
10356 ?        Ssl    3:30              \_ /usr/bin/java -cp ./miui_sb7.jar:/usr                                                      /local/lib/erlang/lib/jinterface-1.6/priv/OtpErlang.jar:/usr/local/lib/erlang/li                                                      b/java_erlang-1.3.1/priv/JavaErlang.jar:/usr/local/lib/erlang/lib/java_erlang-1.                                                      3.1/priv/javassist.jar javaErlang.JavaErlang javaNode_104@203.195.161.84
 2651 ?        Ssl    8:11              \_ /usr/bin/java -cp ./miui_sb7.jar:/usr                                                      /local/lib/erlang/lib/jinterface-1.6/priv/OtpErlang.jar:/usr/local/lib/erlang/li                                                      b/java_erlang-1.3.1/priv/JavaErlang.jar:/usr/local/lib/erlang/lib/java_erlang-1.                                                      3.1/priv/javassist.jar javaErlang.JavaErlang javaNode_107@203.195.161.84
ubuntu@VM-66-105-ubuntu:/data/release/mytest$
